/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 19 17:14:25 GMT 2019
 */

package org.br;

import org.junit.Test;
import static org.junit.Assert.*;
import org.br.Context;
import org.br.TripsConfig;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Context_ESTest extends Context_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TripsConfig tripsConfig0 = Context.initTripsConfig();
      assertEquals(500.0, tripsConfig0.getMinimalTripDistance(), 0.01);
      assertEquals(300000L, tripsConfig0.getMinimalParkingDuration());
      assertEquals(300000L, tripsConfig0.getMinimalTripDuration());
      assertEquals(3600000L, tripsConfig0.getMinimalNoDataDuration());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Context context0 = new Context();
      context0.Context();
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Context context0 = new Context();
      String string0 = context0.getFinal();
      assertNotNull(string0);
  }
}
