/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Jul 08 17:57:57 GMT 2019
 */

package io.cloudslang.lang.api;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class SlangImpl_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "io.cloudslang.lang.api.SlangImpl"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    /*No java.lang.System property to set*/
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(SlangImpl_ESTest_scaffolding.class.getClassLoader() ,
      "io.cloudslang.lang.compiler.SlangCompiler",
      "org.springframework.beans.factory.annotation.Autowired",
      "org.apache.log4j.DefaultCategoryFactory",
      "org.apache.log4j.or.RendererMap",
      "org.python.google.common.io.PatternFilenameFilter",
      "org.apache.commons.lang3.tuple.Pair",
      "org.apache.commons.lang3.builder.IDKey",
      "org.apache.commons.io.filefilter.EmptyFileFilter",
      "org.apache.log4j.Level",
      "org.apache.commons.lang3.builder.HashCodeBuilder",
      "org.apache.commons.io.filefilter.NotFileFilter",
      "org.apache.commons.io.filefilter.TrueFileFilter",
      "org.apache.commons.io.filefilter.AgeFileFilter",
      "io.cloudslang.score.api.TriggeringProperties",
      "org.apache.commons.io.output.ByteArrayOutputStream",
      "org.apache.commons.io.filefilter.ConditionalFileFilter",
      "org.apache.commons.io.filefilter.DirectoryFileFilter",
      "org.apache.commons.io.IOUtils",
      "org.apache.commons.io.filefilter.SuffixFileFilter",
      "org.apache.log4j.CategoryKey",
      "io.cloudslang.score.api.ExecutionPlan",
      "org.apache.log4j.Layout",
      "io.cloudslang.lang.compiler.SlangSource",
      "org.apache.commons.lang.Validate",
      "ch.lambdaj.util.NotUniqueItemException",
      "org.apache.commons.io.filefilter.DelegateFileFilter",
      "org.apache.commons.io.filefilter.AndFileFilter",
      "org.hamcrest.core.IsNot",
      "io.cloudslang.score.events.EventBus",
      "io.cloudslang.lang.entities.CompilationArtifact",
      "org.apache.log4j.helpers.Loader",
      "org.apache.log4j.ProvisionNode",
      "org.apache.log4j.Hierarchy",
      "org.hamcrest.BaseMatcher",
      "org.apache.commons.io.filefilter.NameFileFilter",
      "org.apache.commons.io.output.StringBuilderWriter",
      "io.cloudslang.lang.compiler.modeller.model.Executable",
      "org.apache.commons.lang3.builder.EqualsBuilder",
      "org.apache.commons.io.Charsets",
      "ch.lambdaj.Lambda",
      "org.apache.log4j.spi.DefaultRepositorySelector",
      "org.apache.log4j.spi.OptionHandler",
      "org.apache.log4j.spi.RootLogger",
      "io.cloudslang.score.api.Score",
      "org.apache.log4j.spi.ErrorHandler",
      "org.apache.commons.io.FileUtils",
      "org.apache.log4j.spi.RendererSupport",
      "io.cloudslang.lang.entities.bindings.InOutParam",
      "org.apache.commons.lang3.Validate",
      "org.apache.commons.lang.builder.EqualsBuilder",
      "org.apache.commons.io.filefilter.WildcardFilter",
      "org.hamcrest.Matcher",
      "org.apache.commons.io.output.NullOutputStream",
      "org.apache.commons.io.filefilter.WildcardFileFilter",
      "org.apache.log4j.helpers.AppenderAttachableImpl",
      "org.apache.commons.lang3.exception.CloneFailedException",
      "org.apache.log4j.helpers.OptionConverter",
      "io.cloudslang.score.api.ControlActionMetadata",
      "org.apache.commons.io.filefilter.IOFileFilter",
      "org.hamcrest.core.IsNull",
      "org.apache.commons.io.filefilter.MagicNumberFileFilter",
      "ch.lambdaj.function.aggregate.PairAggregator",
      "org.python.core.packagecache.PathPackageManager$PackageExistsFileFilter",
      "org.apache.log4j.or.ObjectRenderer",
      "ch.lambdaj.function.aggregate.Aggregator",
      "org.apache.log4j.Logger",
      "ch.lambdaj.function.aggregate.Sum",
      "ch.lambdaj.function.aggregate.Chooser",
      "org.apache.log4j.helpers.LogLog",
      "org.apache.log4j.Category",
      "io.cloudslang.score.events.ScoreEventListener",
      "io.cloudslang.score.events.ScoreEvent",
      "io.cloudslang.lang.api.SlangImpl",
      "org.apache.commons.io.filefilter.AbstractFileFilter",
      "ch.lambdaj.function.convert.Converter",
      "org.apache.log4j.spi.RepositorySelector",
      "org.apache.commons.io.filefilter.FileFileFilter",
      "io.cloudslang.lang.entities.bindings.Input",
      "ch.lambdaj.function.aggregate.Min",
      "org.apache.commons.io.filefilter.HiddenFileFilter",
      "org.apache.commons.io.FileExistsException",
      "io.cloudslang.lang.runtime.env.ExecutionPath",
      "org.apache.log4j.spi.LoggerFactory",
      "org.apache.commons.io.filefilter.FalseFileFilter",
      "org.apache.log4j.spi.Configurator",
      "org.apache.log4j.or.DefaultRenderer",
      "org.hamcrest.SelfDescribing",
      "org.apache.commons.io.filefilter.CanReadFileFilter",
      "ch.lambdaj.function.aggregate.Max",
      "org.apache.commons.lang3.ObjectUtils$Null",
      "org.apache.commons.io.IOCase",
      "org.apache.log4j.spi.ThrowableRendererSupport",
      "ch.lambdaj.function.aggregate.Concat",
      "org.apache.commons.lang.builder.HashCodeBuilder",
      "org.apache.log4j.PropertyConfigurator",
      "io.cloudslang.score.api.ExecutionStep",
      "org.apache.commons.lang3.ArrayUtils",
      "org.apache.commons.io.filefilter.SizeFileFilter",
      "org.apache.commons.io.filefilter.OrFileFilter",
      "org.apache.log4j.Appender",
      "org.apache.commons.lang3.ObjectUtils",
      "org.apache.commons.io.filefilter.RegexFileFilter",
      "org.apache.log4j.spi.HierarchyEventListener",
      "io.cloudslang.lang.runtime.env.ContextStack",
      "io.cloudslang.lang.runtime.env.ParentFlowStack",
      "org.apache.log4j.spi.AppenderAttachable",
      "org.hamcrest.Matchers",
      "org.apache.commons.lang3.tuple.ImmutablePair",
      "org.apache.commons.io.filefilter.PrefixFileFilter",
      "org.apache.log4j.Priority",
      "io.cloudslang.lang.api.Slang",
      "ch.lambdaj.function.aggregate.InitializedPairAggregator",
      "org.apache.commons.lang3.builder.Builder",
      "org.apache.log4j.spi.LoggerRepository",
      "org.apache.log4j.LogManager",
      "org.apache.commons.io.filefilter.CanWriteFileFilter",
      "io.cloudslang.lang.runtime.env.RunEnvironment"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(SlangImpl_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.log4j.Category",
      "org.apache.log4j.Logger",
      "org.apache.log4j.Hierarchy",
      "org.apache.log4j.spi.RootLogger",
      "org.apache.log4j.Priority",
      "org.apache.log4j.Level",
      "org.apache.log4j.or.DefaultRenderer",
      "org.apache.log4j.or.RendererMap",
      "org.apache.log4j.DefaultCategoryFactory",
      "org.apache.log4j.spi.DefaultRepositorySelector",
      "org.apache.log4j.helpers.OptionConverter",
      "org.apache.log4j.helpers.Loader",
      "org.apache.log4j.helpers.LogLog",
      "org.apache.log4j.PropertyConfigurator",
      "org.apache.log4j.LogManager",
      "org.apache.log4j.CategoryKey",
      "org.apache.log4j.ProvisionNode",
      "io.cloudslang.lang.api.SlangImpl",
      "io.cloudslang.lang.compiler.SlangSource",
      "org.apache.commons.lang3.Validate",
      "org.apache.commons.lang.Validate",
      "org.hamcrest.Matchers",
      "org.hamcrest.BaseMatcher",
      "org.hamcrest.core.IsNull",
      "org.hamcrest.core.IsNot",
      "ch.lambdaj.function.aggregate.PairAggregator",
      "ch.lambdaj.function.aggregate.InitializedPairAggregator",
      "ch.lambdaj.function.aggregate.Sum",
      "ch.lambdaj.function.aggregate.Chooser",
      "ch.lambdaj.function.aggregate.Min",
      "ch.lambdaj.function.aggregate.Max",
      "ch.lambdaj.function.aggregate.Concat",
      "ch.lambdaj.Lambda",
      "io.cloudslang.score.api.ExecutionPlan",
      "io.cloudslang.score.api.TriggeringProperties",
      "org.apache.commons.io.FileUtils",
      "org.apache.commons.io.output.StringBuilderWriter",
      "org.apache.commons.io.IOUtils",
      "io.cloudslang.score.api.ExecutionStep",
      "io.cloudslang.score.api.ControlActionMetadata",
      "io.cloudslang.lang.entities.CompilationArtifact",
      "io.cloudslang.lang.runtime.env.RunEnvironment",
      "io.cloudslang.lang.runtime.env.ContextStack",
      "io.cloudslang.lang.runtime.env.ParentFlowStack",
      "io.cloudslang.lang.runtime.env.ExecutionPath",
      "io.cloudslang.lang.entities.bindings.InOutParam",
      "io.cloudslang.lang.entities.bindings.Input",
      "org.apache.commons.lang3.builder.HashCodeBuilder",
      "org.apache.commons.io.Charsets",
      "org.apache.commons.lang3.builder.EqualsBuilder",
      "org.apache.commons.lang.builder.EqualsBuilder",
      "org.apache.commons.lang3.builder.IDKey",
      "org.apache.commons.lang3.tuple.Pair",
      "org.apache.commons.lang3.tuple.ImmutablePair",
      "org.apache.commons.lang3.ArrayUtils",
      "org.apache.commons.lang3.ObjectUtils$Null",
      "org.apache.commons.lang3.ObjectUtils",
      "org.apache.commons.lang.builder.HashCodeBuilder"
    );
  }
}
