/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 22 15:11:40 GMT 2019
 */

package org.fusesource.restygwt.rebind;

import org.junit.Test;
import static org.junit.Assert.*;
import com.google.gwt.dev.javac.typemodel.JTypeParameter;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DirectRestServiceInterfaceClassCreator_ESTest extends DirectRestServiceInterfaceClassCreator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // EXCEPTION DIFF:
      // The original version did not exhibit this exception:
      //     java.lang.NoClassDefFoundError : Could not initialize class com.google.gwt.dev.util.StringInterner
      JTypeParameter jTypeParameter0 = new JTypeParameter("", 1);
  }
}
