/*
 * This file was automatically generated by EvoSuite
 * Wed Jun 19 17:09:16 GMT 2019
 */

package org.br;

import org.junit.Test;
import static org.junit.Assert.*;
import org.br.TripsConfig;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TripsConfig_ESTest extends TripsConfig_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TripsConfig tripsConfig0 = new TripsConfig();
      // EXCEPTION DIFF:
      // The original version did not exhibit this exception:
      //     java.lang.IllegalArgumentException : java.lang.ClassCastException@d853ebe
      tripsConfig0.setUseIgnition(true);
  }
}
