/*
 * This file was automatically generated by EvoSuite
 * Tue Jul 09 15:34:48 GMT 2019
 */

package com.zaxxer.hikari.util;

import org.junit.Test;
import static org.junit.Assert.*;
import com.zaxxer.hikari.util.UtilityElf;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UtilityElf_ESTest extends UtilityElf_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      long long0 = UtilityElf.elapsedTimeMs(0L);
      assertEquals(1392409281L, long0); // (Primitive) Original Value: 1392409281 | Regression Value: 1392409281320
  }
}
