/*
 * This file was automatically generated by EvoSuite
 * Thu Aug 08 14:32:11 GMT 2019
 */

package org.apache.storm.kafka.spout;

import org.junit.Test;
import static org.junit.Assert.*;
import org.apache.kafka.common.serialization.IntegerDeserializer;
import org.apache.kafka.common.serialization.StringDeserializer;
import org.apache.storm.kafka.spout.KafkaSpoutConfig;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class KafkaSpoutConfig_ESTest extends KafkaSpoutConfig_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Class<IntegerDeserializer> class0 = IntegerDeserializer.class;
      Class<StringDeserializer> class1 = StringDeserializer.class;
      String[] stringArray0 = new String[9];
      // EXCEPTION DIFF:
      // The original version did not exhibit this exception:
      //     java.lang.IllegalArgumentException : The constructor public org.apache.storm.kafka.spout.KafkaSpoutConfig$Builder(java.lang.String,java.lang.Class,java.lang.Class,java.lang.String[]) is not a member of type org.apache.storm.kafka.spout.KafkaSpoutConfig<org.apache.kafka.common.serialization.LongDeserializer, org.apache.kafka.common.serialization.BytesDeserializer>.Builder<java.lang.Integer, java.lang.String>
      KafkaSpoutConfig.Builder<Integer, String> kafkaSpoutConfig_Builder0 = new KafkaSpoutConfig.Builder<Integer, String>("|XfKovc^/9O0Ssmj>?7", class0, class1, stringArray0);
  }
}
