/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 16 10:18:09 GMT 2019
 */

package org.webbitserver.netty;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.concurrent.LinkedBlockingDeque;
import java.util.concurrent.RejectedExecutionException;
import java.util.concurrent.ThreadFactory;
import java.util.concurrent.ThreadPoolExecutor;
import java.util.concurrent.TimeUnit;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.lang.MockThread;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class WebSocketClient_ESTest extends WebSocketClient_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ThreadPoolExecutor.AbortPolicy threadPoolExecutor_AbortPolicy0 = new ThreadPoolExecutor.AbortPolicy();
      Thread thread0 = MockThread.currentThread();
      TimeUnit timeUnit0 = TimeUnit.MINUTES;
      LinkedBlockingDeque<Runnable> linkedBlockingDeque0 = new LinkedBlockingDeque<Runnable>();
      ThreadFactory threadFactory0 = mock(ThreadFactory.class, new ViolatedAssumptionAnswer());
      ThreadPoolExecutor threadPoolExecutor0 = new ThreadPoolExecutor(198, 709, 709, timeUnit0, linkedBlockingDeque0, threadFactory0, threadPoolExecutor_AbortPolicy0);
      // EXCEPTION DIFF:
      // Different Exceptions were thrown:
      // Original Version:
      //     java.util.concurrent.RejectedExecutionException : Task Thread[pool-1832-thread-2,5,Test_Execution_Group] rejected from java.util.concurrent.ThreadPoolExecutor@65458099[Running, pool size = 0, active threads = 0, queued tasks = 1, completed tasks = 0]
      // Modified Version:
      //     java.util.concurrent.RejectedExecutionException : Task Thread[ForkJoinPool.commonPool-worker-0,5,InnocuousForkJoinWorkerThreadGroup] rejected from java.util.concurrent.ThreadPoolExecutor@29a509e7[Running, pool size = 0, active threads = 0, queued tasks = 1, completed tasks = 0]
      // Undeclared exception!
      try { 
        threadPoolExecutor_AbortPolicy0.rejectedExecution(thread0, threadPoolExecutor0);
       //  fail("Expecting exception: RejectedExecutionException");
       // Unstable assertion
      } catch(RejectedExecutionException e) {
         //
         // Task Thread[pool-1832-thread-2,5,Test_Execution_Group] rejected from java.util.concurrent.ThreadPoolExecutor@6c5eafbe[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
         //
         verifyException("java.util.concurrent.ThreadPoolExecutor$AbortPolicy", e);
         assertTrue(e.getMessage().equals("Task Thread[pool-1832-thread-2,5,Test_Execution_Group] rejected from java.util.concurrent.ThreadPoolExecutor@6c5eafbe[Running, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]"));   
      }
  }
}
