/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Tue Jul 09 14:02:33 GMT 2019
 */

package com.zaxxer.hikari.util;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class ConcurrentBag_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.zaxxer.hikari.util.ConcurrentBag"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "BR"); 
    java.lang.System.setProperty("user.dir", "/home/paulo/Documentos/PHD/Testes2.0/test-analysis-tools/TestCasesGenerated/RealProjects/EvoSuite/hikariCP-c399b46/left"); 
    java.lang.System.setProperty("user.home", "/home/paulo"); 
    java.lang.System.setProperty("user.language", "pt"); 
    java.lang.System.setProperty("user.name", "paulo"); 
    java.lang.System.setProperty("user.timezone", "America/Recife"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ConcurrentBag_ESTest_scaffolding.class.getClassLoader() ,
      "com.zaxxer.hikari.util.Sequence$DropwizardSequence",
      "com.zaxxer.hikari.util.PropertyElf",
      "com.zaxxer.hikari.HikariConfigMXBean",
      "com.zaxxer.hikari.util.FastList",
      "com.zaxxer.hikari.util.UtilityElf",
      "com.zaxxer.hikari.pool.ProxyLeakTask$1",
      "com.zaxxer.hikari.util.ConcurrentBag$1",
      "com.zaxxer.hikari.util.Sequence$Factory",
      "com.zaxxer.hikari.pool.HikariPool$PoolInitializationException",
      "com.zaxxer.hikari.pool.HikariPool$5",
      "com.zaxxer.hikari.util.ConcurrentBag$IConcurrentBagEntry",
      "com.zaxxer.hikari.util.ClockSource$NanosecondClockSource",
      "com.zaxxer.hikari.util.QueuedSequenceSynchronizer",
      "com.zaxxer.hikari.metrics.PoolStats",
      "com.zaxxer.hikari.util.ClockSource",
      "com.zaxxer.hikari.util.SuspendResumeLock$1",
      "com.zaxxer.hikari.util.ConcurrentBag",
      "com.zaxxer.hikari.util.SuspendResumeLock",
      "com.zaxxer.hikari.util.QueuedSequenceSynchronizer$Synchronizer",
      "com.zaxxer.hikari.util.Sequence$Java8Sequence",
      "com.zaxxer.hikari.pool.ProxyLeakTask",
      "com.zaxxer.hikari.pool.PoolBase",
      "com.zaxxer.hikari.util.ClockSource$MillisecondClockSource",
      "com.zaxxer.hikari.util.ConcurrentBag$IBagStateListener",
      "com.zaxxer.hikari.metrics.MetricsTrackerFactory",
      "com.zaxxer.hikari.util.Sequence$Java7Sequence",
      "com.zaxxer.hikari.util.DefaultThreadFactory",
      "com.zaxxer.hikari.metrics.MetricsTracker",
      "com.zaxxer.hikari.util.Sequence",
      "com.zaxxer.hikari.pool.ProxyConnection",
      "com.zaxxer.hikari.HikariConfig",
      "com.zaxxer.hikari.pool.PoolEntry",
      "com.zaxxer.hikari.util.ClockSource$Factory",
      "com.zaxxer.hikari.HikariDataSource",
      "com.zaxxer.hikari.pool.HikariPool$HouseKeeper",
      "com.zaxxer.hikari.metrics.MetricsTracker$MetricsContext",
      "com.zaxxer.hikari.pool.HikariPool",
      "com.zaxxer.hikari.HikariPoolMXBean"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("com.zaxxer.hikari.pool.PoolEntry", false, ConcurrentBag_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ConcurrentBag_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.zaxxer.hikari.util.ConcurrentBag",
      "com.zaxxer.hikari.util.ConcurrentBag$1",
      "com.zaxxer.hikari.HikariConfig",
      "com.zaxxer.hikari.HikariDataSource",
      "com.zaxxer.hikari.pool.PoolBase",
      "com.zaxxer.hikari.util.ClockSource$Factory",
      "com.zaxxer.hikari.util.ClockSource$NanosecondClockSource",
      "com.zaxxer.hikari.util.ClockSource",
      "com.zaxxer.hikari.pool.HikariPool",
      "com.zaxxer.hikari.util.UtilityElf",
      "com.zaxxer.hikari.util.QueuedSequenceSynchronizer",
      "com.zaxxer.hikari.util.QueuedSequenceSynchronizer$Synchronizer",
      "com.zaxxer.hikari.util.Sequence$Factory",
      "com.zaxxer.hikari.util.Sequence$Java8Sequence",
      "com.zaxxer.hikari.util.SuspendResumeLock$1",
      "com.zaxxer.hikari.util.SuspendResumeLock",
      "com.zaxxer.hikari.util.DefaultThreadFactory",
      "com.zaxxer.hikari.pool.HikariPool$HouseKeeper",
      "com.zaxxer.hikari.pool.ProxyLeakTask$1",
      "com.zaxxer.hikari.pool.ProxyLeakTask",
      "com.zaxxer.hikari.metrics.MetricsTracker$MetricsContext",
      "com.zaxxer.hikari.metrics.MetricsTracker",
      "com.zaxxer.hikari.pool.PoolEntry",
      "com.zaxxer.hikari.pool.HikariPool$PoolInitializationException",
      "com.zaxxer.hikari.util.PropertyElf",
      "com.zaxxer.hikari.util.FastList"
    );
  }
}
