/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Mon Jun 17 19:50:09 GMT 2019
 */

package org.apache.storm.kafka.spout;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class KafkaSpoutConfig_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "org.apache.storm.kafka.spout.KafkaSpoutConfig"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "BR"); 
    java.lang.System.setProperty("user.dir", "/home/paulo/Documentos/PHD/Testes2.0/SampleTests/Analysis/RealProjects/EvoSuite/storm"); 
    java.lang.System.setProperty("user.home", "/home/paulo"); 
    java.lang.System.setProperty("user.language", "pt"); 
    java.lang.System.setProperty("user.name", "paulo"); 
    java.lang.System.setProperty("user.timezone", "America/Recife"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(KafkaSpoutConfig_ESTest_scaffolding.class.getClassLoader() ,
      "org.apache.storm.topology.OutputFieldsDeclarer",
      "org.apache.storm.spout.ISpoutOutputCollector",
      "org.apache.storm.kafka.spout.KafkaSpoutRetryService",
      "org.apache.storm.kafka.spout.KafkaSpoutStreamsWildcardTopics",
      "org.apache.storm.kafka.spout.KafkaSpoutConfig$FirstPollOffsetStrategy",
      "org.apache.storm.kafka.spout.SerializableDeserializer",
      "org.apache.storm.kafka.spout.KafkaSpoutRetryExponentialBackoff$RetryEntryTimeStampComparator",
      "org.apache.kafka.common.serialization.Deserializer",
      "org.apache.storm.kafka.spout.KafkaSpoutMessageId",
      "org.apache.storm.kafka.spout.KafkaSpoutConfig",
      "org.apache.storm.task.IErrorReporter",
      "org.apache.kafka.common.record.TimestampType",
      "org.apache.kafka.common.TopicPartition",
      "org.apache.storm.kafka.spout.KafkaSpoutTuplesBuilderWildcardTopics",
      "org.apache.storm.topology.OutputFieldsGetter",
      "org.apache.storm.kafka.spout.KafkaSpoutRetryExponentialBackoff$TimeInterval",
      "org.apache.storm.tuple.Fields",
      "org.apache.storm.kafka.spout.KafkaSpoutTuplesBuilder",
      "org.apache.storm.kafka.spout.KafkaSpoutStream",
      "org.apache.storm.kafka.spout.KafkaSpoutStreamsNamedTopics",
      "org.apache.storm.kafka.spout.KafkaSpoutStreams",
      "org.apache.kafka.clients.consumer.ConsumerRecord",
      "org.apache.storm.kafka.spout.KafkaSpoutTupleBuilder",
      "org.apache.storm.kafka.spout.KafkaSpoutRetryExponentialBackoff",
      "org.apache.storm.kafka.spout.KafkaSpoutConfig$Builder",
      "org.apache.storm.spout.SpoutOutputCollector",
      "org.apache.storm.kafka.spout.KafkaSpoutRetryExponentialBackoff$RetrySchedule"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("org.apache.storm.kafka.spout.KafkaSpoutTupleBuilder", false, KafkaSpoutConfig_ESTest_scaffolding.class.getClassLoader()));
    mock(Class.forName("org.apache.storm.kafka.spout.SerializableDeserializer", false, KafkaSpoutConfig_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(KafkaSpoutConfig_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "org.apache.storm.kafka.spout.KafkaSpoutConfig",
      "org.apache.storm.kafka.spout.KafkaSpoutConfig$Builder",
      "org.apache.storm.kafka.spout.KafkaSpoutConfig$FirstPollOffsetStrategy",
      "org.apache.storm.kafka.spout.KafkaSpoutTupleBuilder",
      "org.apache.storm.kafka.spout.KafkaSpoutTuplesBuilderWildcardTopics",
      "org.apache.storm.kafka.spout.KafkaSpoutRetryExponentialBackoff$TimeInterval",
      "org.apache.kafka.clients.consumer.ConsumerRecord",
      "org.apache.storm.kafka.spout.KafkaSpoutRetryExponentialBackoff$RetryEntryTimeStampComparator",
      "org.apache.storm.kafka.spout.KafkaSpoutRetryExponentialBackoff",
      "org.apache.storm.kafka.spout.KafkaSpoutStream",
      "org.apache.storm.kafka.spout.KafkaSpoutStreamsWildcardTopics",
      "org.apache.storm.tuple.Fields",
      "org.apache.storm.topology.OutputFieldsGetter",
      "org.apache.storm.kafka.spout.KafkaSpoutStreamsNamedTopics",
      "org.apache.kafka.common.TopicPartition",
      "org.apache.storm.kafka.spout.KafkaSpoutMessageId",
      "org.apache.storm.kafka.spout.KafkaSpoutRetryExponentialBackoff$RetrySchedule"
    );
  }
}
