/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Aug 01 18:57:48 GMT 2019
 */

package fitnesse.testsystems.slim.tables;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class SlimTableFactory_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "fitnesse.testsystems.slim.tables.SlimTableFactory"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/tmp"); 
    java.lang.System.setProperty("user.country", "BR"); 
    java.lang.System.setProperty("user.dir", "/home/paulo/Documentos/PHD/Testes2.0/test-analysis-tools/TestCasesGenerated/RealProjects/EvoSuite/fitnesse-4d9ba9d/right"); 
    java.lang.System.setProperty("user.home", "/home/paulo"); 
    java.lang.System.setProperty("user.language", "pt"); 
    java.lang.System.setProperty("user.name", "paulo"); 
    java.lang.System.setProperty("user.timezone", "America/Recife"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(SlimTableFactory_ESTest_scaffolding.class.getClassLoader() ,
      "fitnesse.slim.instructions.ImportInstruction",
      "org.htmlparser.tags.ObjectTag",
      "org.htmlparser.tags.TableTag",
      "org.htmlparser.NodeFactory",
      "org.htmlparser.lexer.PageIndex",
      "org.htmlparser.util.EncodingChangeException",
      "org.htmlparser.filters.OrFilter",
      "org.htmlparser.util.ParserFeedback",
      "fitnesse.slim.instructions.CallAndAssignInstruction",
      "org.htmlparser.tags.AppletTag",
      "fitnesse.testsystems.slim.HtmlTable$Row",
      "org.htmlparser.util.IteratorImpl",
      "fitnesse.testsystems.slim.tables.QueryTable$QueryResults",
      "fitnesse.testsystems.slim.tables.SubsetQueryTable",
      "org.htmlparser.tags.DoctypeTag",
      "fitnesse.testsystems.Instruction",
      "fitnesse.testsystems.slim.tables.ScenarioTable",
      "org.htmlparser.tags.BulletList",
      "org.htmlparser.scanners.ScriptScanner",
      "fitnesse.testsystems.slim.CustomComparatorRegistry",
      "fitnesse.testsystems.slim.tables.ImportTable",
      "fitnesse.testsystems.slim.HtmlTableScanner",
      "org.htmlparser.tags.BlockquoteTag",
      "org.htmlparser.nodes.TagNode",
      "fitnesse.slim.instructions.Instruction$1",
      "org.htmlparser.visitors.UrlModifyingVisitor",
      "org.htmlparser.util.sort.Ordered",
      "org.htmlparser.http.ConnectionManager",
      "fitnesse.testsystems.slim.TableScanner",
      "fitnesse.testsystems.slim.tables.DecisionTable",
      "org.htmlparser.util.ParserException",
      "fitnesse.testsystems.slim.tables.SlimTableFactory",
      "fitnesse.testsystems.slim.tables.ScriptTable",
      "fitnesse.slim.instructions.InstructionResult",
      "org.htmlparser.tags.InputTag",
      "org.htmlparser.visitors.StringFindingVisitor",
      "fitnesse.testsystems.slim.tables.LibraryTable",
      "org.htmlparser.lexer.Page",
      "org.htmlparser.tags.ImageTag",
      "fitnesse.testsystems.slim.tables.SlimTable$SymbolAssignmentExpectation",
      "fitnesse.testsystems.slim.tables.SlimTable$RejectedValueExpectation",
      "org.htmlparser.tags.TableRow",
      "org.htmlparser.tags.ScriptTag",
      "fitnesse.slim.instructions.InstructionExecutor",
      "fitnesse.testsystems.slim.tables.SlimAssertion",
      "org.htmlparser.util.NodeIterator",
      "fitnesse.testsystems.slim.tables.QueryTable",
      "fitnesse.testsystems.slim.SlimTestContext",
      "org.htmlparser.tags.Div",
      "org.htmlparser.scanners.StyleScanner",
      "fitnesse.testsystems.slim.results.SlimExceptionResult",
      "org.htmlparser.tags.TitleTag",
      "org.htmlparser.tags.HeadTag",
      "fitnesse.testsystems.slim.SlimTestContextImpl",
      "org.htmlparser.Attribute",
      "fitnesse.testsystems.slim.tables.SlimTable$FullExpansionSymbolReplacer",
      "fitnesse.slim.instructions.MakeInstruction",
      "fitnesse.slim.NameTranslatorIdentity",
      "org.htmlparser.tags.FrameTag",
      "fitnesse.testsystems.slim.tables.TableTable",
      "fitnesse.testsystems.slim.tables.SyntaxError",
      "org.htmlparser.util.sort.Sort",
      "org.htmlparser.tags.ProcessingInstructionTag",
      "fitnesse.testsystems.slim.Table$CellContentSubstitution",
      "fitnesse.slim.instructions.SystemExitSecurityManager",
      "fitnesse.testsystems.slim.tables.SlimTable$ConstructionExpectation",
      "org.htmlparser.util.SimpleNodeIterator",
      "fitnesse.testsystems.slim.tables.SlimTable$Comparator",
      "org.htmlparser.util.ChainedException",
      "fitnesse.testsystems.slim.tables.ScenarioTable$ScenarioTestContext",
      "org.htmlparser.tags.BaseHrefTag",
      "org.htmlparser.tags.LinkTag",
      "org.htmlparser.tags.BodyTag",
      "org.htmlparser.Tag",
      "org.htmlparser.nodes.AbstractNode",
      "org.htmlparser.Text",
      "org.htmlparser.http.Cookie",
      "fitnesse.testsystems.Expectation",
      "org.htmlparser.tags.FormTag",
      "org.htmlparser.lexer.Lexer",
      "org.htmlparser.lexer.Stream",
      "org.htmlparser.scanners.JspScanner",
      "org.htmlparser.tags.Bullet",
      "org.htmlparser.tags.TextareaTag",
      "org.htmlparser.tags.MetaTag",
      "org.htmlparser.lexer.StringSource",
      "fitnesse.slim.instructions.InstructionResult$Ok",
      "fitnesse.testsystems.Assertion",
      "org.htmlparser.visitors.ObjectFindingVisitor",
      "fitnesse.testsystems.slim.tables.SlimTable$SilentReturnExpectation",
      "org.htmlparser.tags.DefinitionList",
      "fitnesse.testsystems.slim.tables.SlimTable$RowExpectation",
      "fitnesse.testsystems.TestResult",
      "org.htmlparser.lexer.InputStreamSource",
      "org.htmlparser.tags.FrameSetTag",
      "org.htmlparser.tags.ParagraphTag",
      "fitnesse.slim.instructions.InstructionResult$Void",
      "fitnesse.testsystems.slim.CustomComparator",
      "org.htmlparser.scanners.Scanner",
      "fitnesse.slim.instructions.Instruction",
      "org.htmlparser.http.ConnectionMonitor",
      "fitnesse.testsystems.ExceptionResult",
      "fitnesse.testsystems.slim.results.SlimTestResult",
      "org.htmlparser.tags.SelectTag",
      "org.htmlparser.lexer.PageAttribute",
      "fitnesse.testsystems.slim.tables.SlimTable$SymbolReplacer",
      "fitnesse.slim.instructions.SystemExitSecurityManager$SystemExitException",
      "fitnesse.testsystems.slim.tables.SlimErrorTable",
      "org.htmlparser.tags.TableHeader",
      "org.htmlparser.Node",
      "org.htmlparser.lexer.Cursor",
      "fitnesse.testsystems.slim.Table",
      "org.htmlparser.nodes.RemarkNode",
      "fitnesse.testsystems.slim.HtmlTable",
      "org.htmlparser.scanners.CompositeTagScanner",
      "org.htmlparser.tags.Html",
      "fitnesse.slim.NameTranslator",
      "fitnesse.slim.SlimError",
      "org.htmlparser.nodes.TextNode",
      "fitnesse.testsystems.slim.tables.SlimTable",
      "org.htmlparser.tags.OptionTag",
      "fitnesse.testsystems.slim.tables.SlimTable$VoidReturnExpectation",
      "fitnesse.testsystems.slim.tables.SlimExpectation$1",
      "fitnesse.slim.instructions.InstructionResult$Error",
      "fitnesse.testsystems.slim.HtmlTable$Cell",
      "org.htmlparser.visitors.NodeVisitor",
      "org.htmlparser.util.sort.Sortable",
      "org.htmlparser.tags.CompositeTag",
      "fitnesse.slim.SlimException",
      "org.htmlparser.tags.JspTag",
      "org.htmlparser.util.NodeList$1",
      "org.htmlparser.NodeFilter",
      "org.htmlparser.scanners.TagScanner",
      "fitnesse.testsystems.TestSummary$1",
      "fitnesse.testsystems.slim.tables.OrderedQueryTable",
      "org.htmlparser.tags.Span",
      "org.htmlparser.util.NodeList",
      "fitnesse.testsystems.TestSummary",
      "fitnesse.testsystems.slim.tables.SlimTable$ReturnedValueExpectation",
      "fitnesse.testsystems.slim.tables.SlimExpectation",
      "org.htmlparser.util.DefaultParserFeedback",
      "org.htmlparser.tags.DefinitionListBullet",
      "org.htmlparser.visitors.TagFindingVisitor",
      "org.htmlparser.lexer.Source",
      "fitnesse.slim.instructions.CallInstruction",
      "org.htmlparser.Remark",
      "org.htmlparser.tags.HeadingTag",
      "org.htmlparser.tags.StyleTag",
      "fitnesse.util.HtmlParserTools",
      "org.htmlparser.PrototypicalNodeFactory",
      "org.htmlparser.Parser",
      "fitnesse.testsystems.ExecutionResult",
      "org.htmlparser.tags.LabelTag",
      "fitnesse.testsystems.TableCell",
      "fitnesse.testsystems.slim.tables.SlimTable$Disgracer",
      "org.htmlparser.tags.TableColumn"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(SlimTableFactory_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "fitnesse.testsystems.slim.tables.SlimTableFactory",
      "fitnesse.testsystems.slim.SlimTestContextImpl",
      "fitnesse.testsystems.TestSummary",
      "fitnesse.testsystems.slim.tables.SlimTable",
      "fitnesse.testsystems.slim.tables.ScenarioTable",
      "org.htmlparser.nodes.AbstractNode",
      "org.htmlparser.scanners.TagScanner",
      "org.htmlparser.nodes.TagNode",
      "org.htmlparser.scanners.CompositeTagScanner",
      "org.htmlparser.tags.CompositeTag",
      "org.htmlparser.tags.TableTag",
      "org.htmlparser.Attribute",
      "fitnesse.testsystems.slim.HtmlTable",
      "org.htmlparser.util.NodeList",
      "org.htmlparser.util.NodeList$1",
      "fitnesse.testsystems.TestSummary$1",
      "org.htmlparser.lexer.Lexer",
      "org.htmlparser.http.ConnectionManager",
      "org.htmlparser.lexer.Page",
      "fitnesse.slim.NameTranslatorIdentity",
      "fitnesse.slim.instructions.Instruction$1",
      "fitnesse.slim.instructions.Instruction",
      "fitnesse.slim.instructions.CallAndAssignInstruction",
      "org.htmlparser.scanners.ScriptScanner",
      "org.htmlparser.scanners.JspScanner",
      "org.htmlparser.lexer.Source",
      "org.htmlparser.lexer.StringSource",
      "org.htmlparser.lexer.PageIndex",
      "org.htmlparser.lexer.Cursor",
      "org.htmlparser.nodes.TextNode",
      "fitnesse.testsystems.slim.tables.ImportTable",
      "org.htmlparser.filters.OrFilter",
      "fitnesse.testsystems.slim.tables.LibraryTable",
      "org.htmlparser.tags.FormTag",
      "org.htmlparser.tags.InputTag",
      "fitnesse.testsystems.slim.HtmlTableScanner",
      "org.htmlparser.util.DefaultParserFeedback",
      "org.htmlparser.Parser",
      "org.htmlparser.PrototypicalNodeFactory",
      "org.htmlparser.nodes.RemarkNode",
      "org.htmlparser.tags.AppletTag",
      "org.htmlparser.tags.BaseHrefTag",
      "org.htmlparser.tags.Bullet",
      "org.htmlparser.tags.BulletList",
      "org.htmlparser.tags.DefinitionList",
      "org.htmlparser.tags.DefinitionListBullet",
      "org.htmlparser.tags.DoctypeTag",
      "org.htmlparser.tags.FrameSetTag",
      "org.htmlparser.tags.FrameTag",
      "org.htmlparser.tags.HeadingTag",
      "org.htmlparser.tags.ImageTag",
      "org.htmlparser.tags.JspTag",
      "org.htmlparser.tags.LabelTag",
      "org.htmlparser.tags.LinkTag",
      "org.htmlparser.tags.MetaTag",
      "org.htmlparser.tags.ObjectTag",
      "org.htmlparser.tags.OptionTag",
      "org.htmlparser.tags.ParagraphTag",
      "org.htmlparser.tags.ProcessingInstructionTag",
      "org.htmlparser.tags.ScriptTag",
      "org.htmlparser.tags.SelectTag",
      "org.htmlparser.tags.StyleTag",
      "org.htmlparser.scanners.StyleScanner",
      "org.htmlparser.tags.TableColumn",
      "org.htmlparser.tags.TableHeader",
      "org.htmlparser.tags.TableRow",
      "org.htmlparser.tags.TextareaTag",
      "org.htmlparser.tags.TitleTag",
      "org.htmlparser.tags.Div",
      "org.htmlparser.tags.BlockquoteTag",
      "org.htmlparser.tags.Span",
      "org.htmlparser.tags.BodyTag",
      "org.htmlparser.tags.HeadTag",
      "org.htmlparser.tags.Html",
      "org.htmlparser.util.IteratorImpl",
      "org.htmlparser.lexer.PageAttribute",
      "fitnesse.util.HtmlParserTools",
      "org.htmlparser.visitors.NodeVisitor",
      "org.htmlparser.visitors.UrlModifyingVisitor",
      "fitnesse.testsystems.slim.tables.QueryTable",
      "fitnesse.testsystems.slim.tables.SubsetQueryTable",
      "org.htmlparser.visitors.TagFindingVisitor",
      "org.htmlparser.visitors.ObjectFindingVisitor",
      "fitnesse.testsystems.slim.tables.OrderedQueryTable",
      "fitnesse.slim.instructions.CallInstruction",
      "fitnesse.testsystems.slim.tables.SlimTable$Disgracer",
      "fitnesse.testsystems.slim.tables.SlimTable$RowExpectation",
      "fitnesse.testsystems.slim.tables.SlimTable$ReturnedValueExpectation",
      "org.htmlparser.util.sort.Sort",
      "org.htmlparser.visitors.StringFindingVisitor"
    );
  }
}
