/*
 * This file was automatically generated by EvoSuite
 * Wed Oct 16 12:45:43 GMT 2019
 */

package org.activiti.engine.impl.persistence.entity;

import org.junit.Test;
import static org.junit.Assert.*;
import org.activiti.bpmn.model.ServiceTask;
import org.activiti.engine.impl.bpmn.parser.factory.DefaultActivityBehaviorFactory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DeploymentEntityManager_ESTest extends DeploymentEntityManager_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      DefaultActivityBehaviorFactory defaultActivityBehaviorFactory0 = new DefaultActivityBehaviorFactory();
      ServiceTask serviceTask0 = new ServiceTask();
      // EXCEPTION DIFF:
      // The original version did not exhibit this exception:
      //     java.lang.ClassCastException : org.activiti.engine.impl.bpmn.behavior.ShellActivityBehavior cannot be cast to org.activiti.engine.impl.bpmn.behavior.ShellActivityBehavior
      defaultActivityBehaviorFactory0.createShellActivityBehavior(serviceTask0);
  }
}
