/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 08 18:04:07 GMT 2019
 */

package io.cloudslang.lang.api;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import io.cloudslang.lang.api.SlangImpl;
import io.cloudslang.lang.compiler.SlangCompiler;
import io.cloudslang.lang.compiler.SlangSource;
import io.cloudslang.lang.entities.CompilationArtifact;
import io.cloudslang.lang.entities.bindings.Input;
import io.cloudslang.score.api.ExecutionPlan;
import io.cloudslang.score.api.ExecutionStep;
import io.cloudslang.score.api.Score;
import io.cloudslang.score.api.TriggeringProperties;
import io.cloudslang.score.events.EventBus;
import io.cloudslang.score.events.ScoreEventListener;
import java.io.Serializable;
import java.time.ZoneId;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.javaee.injection.Injector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SlangImpl_ESTest extends SlangImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      SlangImpl slangImpl0 = new SlangImpl();
      SlangCompiler slangCompiler0 = mock(SlangCompiler.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "compiler", (Object) slangCompiler0);
      EventBus eventBus0 = mock(EventBus.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "eventBus", (Object) eventBus0);
      Score score0 = mock(Score.class, new ViolatedAssumptionAnswer());
      doReturn((Long) null).when(score0).trigger(any(io.cloudslang.score.api.TriggeringProperties.class));
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "score", (Object) score0);
      Injector.validateBean(slangImpl0, (Class<?>) SlangImpl.class);
      ExecutionPlan executionPlan0 = new ExecutionPlan();
      TriggeringProperties triggeringProperties0 = TriggeringProperties.create(executionPlan0);
      Map<String, ExecutionPlan> map0 = triggeringProperties0.getDependencies();
      LinkedList<Input> linkedList0 = new LinkedList<Input>();
      CompilationArtifact compilationArtifact0 = new CompilationArtifact(executionPlan0, map0, linkedList0, (Collection<Input>) null);
      slangImpl0.run(compilationArtifact0, map0, map0);
      assertEquals(0, map0.size());
      assertTrue(map0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      SlangImpl slangImpl0 = new SlangImpl();
      SlangCompiler slangCompiler0 = mock(SlangCompiler.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "compiler", (Object) slangCompiler0);
      EventBus eventBus0 = mock(EventBus.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "eventBus", (Object) eventBus0);
      Long long0 = new Long((-222L));
      Score score0 = mock(Score.class, new ViolatedAssumptionAnswer());
      doReturn(long0).when(score0).trigger(any(io.cloudslang.score.api.TriggeringProperties.class));
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "score", (Object) score0);
      Injector.validateBean(slangImpl0, (Class<?>) SlangImpl.class);
      ExecutionPlan executionPlan0 = new ExecutionPlan();
      TriggeringProperties triggeringProperties0 = TriggeringProperties.create(executionPlan0);
      Map<String, ExecutionPlan> map0 = triggeringProperties0.getDependencies();
      LinkedList<Input> linkedList0 = new LinkedList<Input>();
      CompilationArtifact compilationArtifact0 = new CompilationArtifact(executionPlan0, map0, linkedList0, (Collection<Input>) null);
      slangImpl0.run(compilationArtifact0, map0, map0);
      assertTrue(map0.isEmpty());
      assertEquals(0, map0.size());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      SlangImpl slangImpl0 = new SlangImpl();
      SlangCompiler slangCompiler0 = mock(SlangCompiler.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "compiler", (Object) slangCompiler0);
      EventBus eventBus0 = mock(EventBus.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "eventBus", (Object) eventBus0);
      Score score0 = mock(Score.class, new ViolatedAssumptionAnswer());
      doReturn((Long) null).when(score0).trigger(any(io.cloudslang.score.api.TriggeringProperties.class));
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "score", (Object) score0);
      Injector.validateBean(slangImpl0, (Class<?>) SlangImpl.class);
      ExecutionPlan executionPlan0 = new ExecutionPlan();
      LinkedList<ExecutionStep> linkedList0 = new LinkedList<ExecutionStep>();
      ExecutionPlan executionPlan1 = executionPlan0.addSteps(linkedList0);
      ExecutionPlan executionPlan2 = executionPlan1.setFlowUuid("");
      TriggeringProperties triggeringProperties0 = TriggeringProperties.create(executionPlan0);
      Long long0 = new Long(0L);
      TriggeringProperties triggeringProperties1 = triggeringProperties0.setStartStep(long0);
      Map<String, ExecutionPlan> map0 = triggeringProperties1.getDependencies();
      LinkedList<Input> linkedList1 = new LinkedList<Input>();
      CompilationArtifact compilationArtifact0 = new CompilationArtifact(executionPlan2, map0, linkedList1, linkedList1);
      Map<String, String> map1 = ZoneId.SHORT_IDS;
      slangImpl0.run(compilationArtifact0, map0, map1);
      assertTrue(map0.isEmpty());
      assertEquals(0, map0.size());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      SlangImpl slangImpl0 = new SlangImpl();
      SlangCompiler slangCompiler0 = mock(SlangCompiler.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "compiler", (Object) slangCompiler0);
      EventBus eventBus0 = mock(EventBus.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "eventBus", (Object) eventBus0);
      Long long0 = new Long(60000L);
      Score score0 = mock(Score.class, new ViolatedAssumptionAnswer());
      doReturn(long0).when(score0).trigger(any(io.cloudslang.score.api.TriggeringProperties.class));
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "score", (Object) score0);
      Injector.validateBean(slangImpl0, (Class<?>) SlangImpl.class);
      ExecutionPlan executionPlan0 = new ExecutionPlan();
      TriggeringProperties triggeringProperties0 = TriggeringProperties.create(executionPlan0);
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      Map<String, ExecutionPlan> map0 = triggeringProperties0.getDependencies();
      LinkedList<Input> linkedList0 = new LinkedList<Input>();
      CompilationArtifact compilationArtifact0 = new CompilationArtifact(executionPlan0, map0, linkedList0, linkedList0);
      slangImpl0.run(compilationArtifact0, hashMap0, hashMap0);
      assertEquals(0, hashMap0.size());
      assertTrue(hashMap0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      SlangImpl slangImpl0 = new SlangImpl();
      ExecutionPlan executionPlan0 = new ExecutionPlan();
      HashMap<String, ExecutionPlan> hashMap0 = new HashMap<String, ExecutionPlan>();
      CompilationArtifact compilationArtifact0 = new CompilationArtifact(executionPlan0, hashMap0, (List<Input>) null, (Collection<Input>) null);
      SlangCompiler slangCompiler0 = mock(SlangCompiler.class, new ViolatedAssumptionAnswer());
      doReturn((CompilationArtifact) null, compilationArtifact0).when(slangCompiler0).compile(any(io.cloudslang.lang.compiler.SlangSource.class) , anySet());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "compiler", (Object) slangCompiler0);
      EventBus eventBus0 = mock(EventBus.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "eventBus", (Object) eventBus0);
      Long long0 = new Long((-3143L));
      Score score0 = mock(Score.class, new ViolatedAssumptionAnswer());
      doReturn(long0).when(score0).trigger(any(io.cloudslang.score.api.TriggeringProperties.class));
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "score", (Object) score0);
      Injector.validateBean(slangImpl0, (Class<?>) SlangImpl.class);
      byte[] byteArray0 = new byte[2];
      SlangSource slangSource0 = SlangSource.fromBytes(byteArray0, "SCORE_ERROR_EVENT");
      LinkedHashSet<SlangSource> linkedHashSet0 = new LinkedHashSet<SlangSource>();
      slangImpl0.compile(slangSource0, linkedHashSet0);
      HashMap<String, String> hashMap1 = new HashMap<String, String>();
      slangImpl0.compileAndRun(slangSource0, linkedHashSet0, hashMap1, hashMap1);
      assertTrue(hashMap1.isEmpty());
      assertEquals(0, hashMap1.size());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      SlangImpl slangImpl0 = new SlangImpl();
      ExecutionPlan executionPlan0 = new ExecutionPlan();
      TriggeringProperties.create(executionPlan0);
      HashMap<String, ExecutionPlan> hashMap0 = new HashMap<String, ExecutionPlan>();
      CompilationArtifact compilationArtifact0 = new CompilationArtifact(executionPlan0, hashMap0, (List<Input>) null, (Collection<Input>) null);
      SlangCompiler slangCompiler0 = mock(SlangCompiler.class, new ViolatedAssumptionAnswer());
      doReturn((CompilationArtifact) null, compilationArtifact0).when(slangCompiler0).compile(any(io.cloudslang.lang.compiler.SlangSource.class) , anySet());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "compiler", (Object) slangCompiler0);
      EventBus eventBus0 = mock(EventBus.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "eventBus", (Object) eventBus0);
      Score score0 = mock(Score.class, new ViolatedAssumptionAnswer());
      doReturn((Long) null).when(score0).trigger(any(io.cloudslang.score.api.TriggeringProperties.class));
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "score", (Object) score0);
      Injector.validateBean(slangImpl0, (Class<?>) SlangImpl.class);
      byte[] byteArray0 = new byte[2];
      SlangSource slangSource0 = SlangSource.fromBytes(byteArray0, "SCORE_ERROR_EVENT");
      LinkedHashSet<SlangSource> linkedHashSet0 = new LinkedHashSet<SlangSource>();
      slangImpl0.compile(slangSource0, linkedHashSet0);
      HashMap<String, String> hashMap1 = new HashMap<String, String>();
      slangImpl0.compileAndRun(slangSource0, linkedHashSet0, hashMap1, hashMap1);
      assertTrue(hashMap1.isEmpty());
      assertEquals(0, hashMap1.size());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      SlangImpl slangImpl0 = new SlangImpl();
      ExecutionPlan executionPlan0 = new ExecutionPlan();
      TriggeringProperties triggeringProperties0 = TriggeringProperties.create(executionPlan0);
      Map<String, ExecutionPlan> map0 = triggeringProperties0.getDependencies();
      CompilationArtifact compilationArtifact0 = mock(CompilationArtifact.class, new ViolatedAssumptionAnswer());
      doReturn(map0).when(compilationArtifact0).getDependencies();
      doReturn(executionPlan0).when(compilationArtifact0).getExecutionPlan();
      doReturn("M)7-vm").when(compilationArtifact0).toString();
      SlangCompiler slangCompiler0 = mock(SlangCompiler.class, new ViolatedAssumptionAnswer());
      doReturn(compilationArtifact0).when(slangCompiler0).compile(any(io.cloudslang.lang.compiler.SlangSource.class) , anySet());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "compiler", (Object) slangCompiler0);
      EventBus eventBus0 = mock(EventBus.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "eventBus", (Object) eventBus0);
      Long long0 = new Long(100L);
      Score score0 = mock(Score.class, new ViolatedAssumptionAnswer());
      doReturn(long0).when(score0).trigger(any(io.cloudslang.score.api.TriggeringProperties.class));
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "score", (Object) score0);
      Injector.validateBean(slangImpl0, (Class<?>) SlangImpl.class);
      SlangSource slangSource0 = new SlangSource("q$4f&Z~ux", "<=");
      LinkedHashSet<SlangSource> linkedHashSet0 = new LinkedHashSet<SlangSource>();
      HashMap<String, ExecutionStep> hashMap0 = new HashMap<String, ExecutionStep>();
      slangImpl0.compileAndRun(slangSource0, linkedHashSet0, hashMap0, hashMap0);
      assertEquals(0, hashMap0.size());
      assertTrue(hashMap0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      SlangImpl slangImpl0 = new SlangImpl();
      HashMap<String, ExecutionPlan> hashMap0 = new HashMap<String, ExecutionPlan>();
      LinkedList<Input> linkedList0 = new LinkedList<Input>();
      CompilationArtifact compilationArtifact0 = new CompilationArtifact((ExecutionPlan) null, hashMap0, linkedList0, linkedList0);
      SlangCompiler slangCompiler0 = mock(SlangCompiler.class, new ViolatedAssumptionAnswer());
      doReturn(compilationArtifact0).when(slangCompiler0).compile(any(io.cloudslang.lang.compiler.SlangSource.class) , anySet());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "compiler", (Object) slangCompiler0);
      EventBus eventBus0 = mock(EventBus.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "eventBus", (Object) eventBus0);
      Score score0 = mock(Score.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "score", (Object) score0);
      Injector.validateBean(slangImpl0, (Class<?>) SlangImpl.class);
      SlangSource slangSource0 = new SlangSource("", "");
      LinkedHashSet<SlangSource> linkedHashSet0 = new LinkedHashSet<SlangSource>();
      CompilationArtifact compilationArtifact1 = slangImpl0.compile(slangSource0, linkedHashSet0);
      assertSame(compilationArtifact1, compilationArtifact0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      SlangImpl slangImpl0 = new SlangImpl();
      SlangCompiler slangCompiler0 = mock(SlangCompiler.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "compiler", (Object) slangCompiler0);
      EventBus eventBus0 = mock(EventBus.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "eventBus", (Object) eventBus0);
      Score score0 = mock(Score.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "score", (Object) score0);
      Injector.validateBean(slangImpl0, (Class<?>) SlangImpl.class);
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      // Undeclared exception!
      try { 
        slangImpl0.run((CompilationArtifact) null, map0, map0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Compilation artifact can not be null
         //
         verifyException("org.apache.commons.lang.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      SlangImpl slangImpl0 = new SlangImpl();
      SlangSource slangSource0 = new SlangSource("5q%&O", "5q%&O");
      LinkedHashSet<SlangSource> linkedHashSet0 = new LinkedHashSet<SlangSource>();
      // Undeclared exception!
      try { 
        slangImpl0.compileAndRun(slangSource0, linkedHashSet0, (Map<String, ? extends Serializable>) null, (Map<String, ? extends Serializable>) null);
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // java.lang.NullPointerException
         //
         verifyException("io.cloudslang.lang.api.SlangImpl", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      SlangImpl slangImpl0 = new SlangImpl();
      SlangCompiler slangCompiler0 = mock(SlangCompiler.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "compiler", (Object) slangCompiler0);
      EventBus eventBus0 = mock(EventBus.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "eventBus", (Object) eventBus0);
      Score score0 = mock(Score.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "score", (Object) score0);
      Injector.validateBean(slangImpl0, (Class<?>) SlangImpl.class);
      HashMap<String, ExecutionPlan> hashMap0 = new HashMap<String, ExecutionPlan>();
      HashMap<String, Integer> hashMap1 = new HashMap<String, Integer>();
      LinkedHashSet<SlangSource> linkedHashSet0 = new LinkedHashSet<SlangSource>(3253);
      // Undeclared exception!
      try { 
        slangImpl0.compileAndRun((SlangSource) null, linkedHashSet0, hashMap1, hashMap0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Source can not be null
         //
         verifyException("org.apache.commons.lang.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      SlangImpl slangImpl0 = new SlangImpl();
      SlangCompiler slangCompiler0 = mock(SlangCompiler.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "compiler", (Object) slangCompiler0);
      EventBus eventBus0 = mock(EventBus.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "eventBus", (Object) eventBus0);
      Score score0 = mock(Score.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "score", (Object) score0);
      Injector.validateBean(slangImpl0, (Class<?>) SlangImpl.class);
      LinkedList<SlangSource> linkedList0 = new LinkedList<SlangSource>();
      LinkedHashSet<SlangSource> linkedHashSet0 = new LinkedHashSet<SlangSource>(linkedList0);
      // Undeclared exception!
      try { 
        slangImpl0.compile((SlangSource) null, linkedHashSet0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Source can not be null
         //
         verifyException("org.apache.commons.lang.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      SlangImpl slangImpl0 = new SlangImpl();
      SlangCompiler slangCompiler0 = mock(SlangCompiler.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "compiler", (Object) slangCompiler0);
      EventBus eventBus0 = mock(EventBus.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "eventBus", (Object) eventBus0);
      Score score0 = mock(Score.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "score", (Object) score0);
      Injector.validateBean(slangImpl0, (Class<?>) SlangImpl.class);
      LinkedList<Input> linkedList0 = new LinkedList<Input>();
      CompilationArtifact compilationArtifact0 = new CompilationArtifact((ExecutionPlan) null, (Map<String, ExecutionPlan>) null, linkedList0, linkedList0);
      // Undeclared exception!
      try { 
        slangImpl0.run(compilationArtifact0, (Map<String, ? extends Serializable>) null, (Map<String, ? extends Serializable>) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("io.cloudslang.score.api.TriggeringProperties", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      SlangImpl slangImpl0 = new SlangImpl();
      SlangCompiler slangCompiler0 = mock(SlangCompiler.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "compiler", (Object) slangCompiler0);
      EventBus eventBus0 = mock(EventBus.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "eventBus", (Object) eventBus0);
      Long long0 = new Long(223L);
      Score score0 = mock(Score.class, new ViolatedAssumptionAnswer());
      doReturn(long0).when(score0).trigger(any(io.cloudslang.score.api.TriggeringProperties.class));
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "score", (Object) score0);
      Injector.validateBean(slangImpl0, (Class<?>) SlangImpl.class);
      ExecutionPlan executionPlan0 = new ExecutionPlan();
      HashMap<String, ExecutionPlan> hashMap0 = new HashMap<String, ExecutionPlan>();
      CompilationArtifact compilationArtifact0 = new CompilationArtifact(executionPlan0, hashMap0, (List<Input>) null, (Collection<Input>) null);
      HashMap<String, Integer> hashMap1 = new HashMap<String, Integer>();
      slangImpl0.run(compilationArtifact0, hashMap0, hashMap1);
      assertTrue(hashMap1.isEmpty());
      assertTrue(hashMap0.isEmpty());
      assertEquals(0, hashMap0.size());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      SlangImpl slangImpl0 = new SlangImpl();
      SlangCompiler slangCompiler0 = mock(SlangCompiler.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "compiler", (Object) slangCompiler0);
      EventBus eventBus0 = mock(EventBus.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "eventBus", (Object) eventBus0);
      Score score0 = mock(Score.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "score", (Object) score0);
      Injector.validateBean(slangImpl0, (Class<?>) SlangImpl.class);
      ScoreEventListener scoreEventListener0 = mock(ScoreEventListener.class, new ViolatedAssumptionAnswer());
      Set<String> set0 = ZoneId.getAvailableZoneIds();
      slangImpl0.subscribeOnEvents(scoreEventListener0, set0);
      assertFalse(set0.contains("compiler"));
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      SlangImpl slangImpl0 = new SlangImpl();
      SlangCompiler slangCompiler0 = mock(SlangCompiler.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "compiler", (Object) slangCompiler0);
      EventBus eventBus0 = mock(EventBus.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "eventBus", (Object) eventBus0);
      Score score0 = mock(Score.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "score", (Object) score0);
      Injector.validateBean(slangImpl0, (Class<?>) SlangImpl.class);
      ScoreEventListener scoreEventListener0 = mock(ScoreEventListener.class, new ViolatedAssumptionAnswer());
      slangImpl0.unSubscribeOnEvents(scoreEventListener0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      SlangImpl slangImpl0 = new SlangImpl();
      ExecutionPlan executionPlan0 = new ExecutionPlan();
      CompilationArtifact compilationArtifact0 = mock(CompilationArtifact.class, new ViolatedAssumptionAnswer());
      doReturn((Map<String, ExecutionPlan>) null).when(compilationArtifact0).getDependencies();
      doReturn(executionPlan0).when(compilationArtifact0).getExecutionPlan();
      doReturn("UyDS%h<op@1EPRl)v+[").when(compilationArtifact0).toString();
      SlangCompiler slangCompiler0 = mock(SlangCompiler.class, new ViolatedAssumptionAnswer());
      doReturn((CompilationArtifact) null, compilationArtifact0).when(slangCompiler0).compile(any(io.cloudslang.lang.compiler.SlangSource.class) , anySet());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "compiler", (Object) slangCompiler0);
      EventBus eventBus0 = mock(EventBus.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "eventBus", (Object) eventBus0);
      Score score0 = mock(Score.class, new ViolatedAssumptionAnswer());
      doReturn((Long) null).when(score0).trigger(any(io.cloudslang.score.api.TriggeringProperties.class));
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "score", (Object) score0);
      Injector.validateBean(slangImpl0, (Class<?>) SlangImpl.class);
      byte[] byteArray0 = new byte[2];
      SlangSource slangSource0 = SlangSource.fromBytes(byteArray0, "SCORE_ERROR_EVENT");
      LinkedHashSet<SlangSource> linkedHashSet0 = new LinkedHashSet<SlangSource>();
      slangImpl0.compile(slangSource0, linkedHashSet0);
      HashMap<String, String> hashMap0 = new HashMap<String, String>();
      slangImpl0.compileAndRun(slangSource0, linkedHashSet0, (Map<String, ? extends Serializable>) null, hashMap0);
      assertEquals(0, hashMap0.size());
      assertTrue(hashMap0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      SlangImpl slangImpl0 = new SlangImpl();
      CompilationArtifact compilationArtifact0 = mock(CompilationArtifact.class, new ViolatedAssumptionAnswer());
      doReturn((ExecutionPlan) null).when(compilationArtifact0).getExecutionPlan();
      doReturn((String) null).when(compilationArtifact0).toString();
      SlangCompiler slangCompiler0 = mock(SlangCompiler.class, new ViolatedAssumptionAnswer());
      doReturn(compilationArtifact0).when(slangCompiler0).compile(any(io.cloudslang.lang.compiler.SlangSource.class) , anySet());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "compiler", (Object) slangCompiler0);
      EventBus eventBus0 = mock(EventBus.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "eventBus", (Object) eventBus0);
      Score score0 = mock(Score.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "score", (Object) score0);
      Injector.validateBean(slangImpl0, (Class<?>) SlangImpl.class);
      SlangSource slangSource0 = new SlangSource("\" has no closing brace. Opening brace at position ", "runEnv");
      Map<String, String> map0 = ZoneId.SHORT_IDS;
      // Undeclared exception!
      try { 
        slangImpl0.compileAndRun(slangSource0, (Set<SlangSource>) null, map0, map0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("io.cloudslang.score.api.TriggeringProperties", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      SlangImpl slangImpl0 = new SlangImpl();
      SlangCompiler slangCompiler0 = mock(SlangCompiler.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "compiler", (Object) slangCompiler0);
      EventBus eventBus0 = mock(EventBus.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "eventBus", (Object) eventBus0);
      Score score0 = mock(Score.class, new ViolatedAssumptionAnswer());
      Injector.inject(slangImpl0, (Class<?>) SlangImpl.class, "score", (Object) score0);
      Injector.validateBean(slangImpl0, (Class<?>) SlangImpl.class);
      ScoreEventListener scoreEventListener0 = mock(ScoreEventListener.class, new ViolatedAssumptionAnswer());
      slangImpl0.subscribeOnAllEvents(scoreEventListener0);
  }
}
