/*
 * This file was automatically generated by EvoSuite
 * Mon Jul 22 16:00:47 GMT 2019
 */

package org.fusesource.restygwt.rebind;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.google.gwt.core.ext.GeneratorContext;
import com.google.gwt.core.ext.NonIncrementalGeneratorContext;
import com.google.gwt.core.ext.StubGeneratorContext;
import com.google.gwt.core.ext.TreeLogger;
import com.google.gwt.dev.javac.typemodel.JClassType;
import com.google.gwt.dev.javac.typemodel.JGenericType;
import com.google.gwt.dev.javac.typemodel.JPackage;
import com.google.gwt.dev.javac.typemodel.JParameterizedType;
import com.google.gwt.dev.javac.typemodel.JTypeParameter;
import com.google.gwt.dev.javac.typemodel.TypeOracle;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.fusesource.restygwt.rebind.DirectRestServiceInterfaceClassCreator;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DirectRestServiceInterfaceClassCreator_ESTest extends DirectRestServiceInterfaceClassCreator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      TreeLogger treeLogger0 = TreeLogger.NULL;
      StubGeneratorContext stubGeneratorContext0 = new StubGeneratorContext();
      GeneratorContext generatorContext0 = NonIncrementalGeneratorContext.newInstance(stubGeneratorContext0);
      TypeOracle typeOracle0 = new TypeOracle();
      JPackage jPackage0 = typeOracle0.getOrCreatePackage("G");
      JGenericType jGenericType0 = new JGenericType(typeOracle0, jPackage0, "G", "", false, (JTypeParameter[]) null);
      JParameterizedType jParameterizedType0 = jGenericType0.asParameterizedByWildcards();
      DirectRestServiceInterfaceClassCreator directRestServiceInterfaceClassCreator0 = new DirectRestServiceInterfaceClassCreator(treeLogger0, generatorContext0, jParameterizedType0);
      // Undeclared exception!
      try { 
        directRestServiceInterfaceClassCreator0.generate();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.gwt.dev.javac.typemodel.JParameterizedType", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      TreeLogger treeLogger0 = TreeLogger.NULL;
      StubGeneratorContext stubGeneratorContext0 = new StubGeneratorContext();
      JTypeParameter jTypeParameter0 = new JTypeParameter("", 0);
      JClassType[] jClassTypeArray0 = new JClassType[9];
      jClassTypeArray0[0] = (JClassType) jTypeParameter0;
      jTypeParameter0.setBounds(jClassTypeArray0);
      DirectRestServiceInterfaceClassCreator directRestServiceInterfaceClassCreator0 = null;
      try {
        directRestServiceInterfaceClassCreator0 = new DirectRestServiceInterfaceClassCreator(treeLogger0, stubGeneratorContext0, jTypeParameter0);
        fail("Expecting exception: StackOverflowError");
      
      } catch(StackOverflowError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      StubGeneratorContext stubGeneratorContext0 = new StubGeneratorContext();
      GeneratorContext generatorContext0 = NonIncrementalGeneratorContext.newInstance(stubGeneratorContext0);
      DirectRestServiceInterfaceClassCreator directRestServiceInterfaceClassCreator0 = null;
      try {
        directRestServiceInterfaceClassCreator0 = new DirectRestServiceInterfaceClassCreator((TreeLogger) null, generatorContext0, (com.google.gwt.core.ext.typeinfo.JClassType) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.fusesource.restygwt.rebind.BaseSourceCreator", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      TreeLogger treeLogger0 = TreeLogger.NULL;
      StubGeneratorContext stubGeneratorContext0 = new StubGeneratorContext();
      GeneratorContext generatorContext0 = NonIncrementalGeneratorContext.newInstance(stubGeneratorContext0);
      TypeOracle typeOracle0 = new TypeOracle();
      JPackage jPackage0 = typeOracle0.getOrCreatePackage("G");
      JGenericType jGenericType0 = new JGenericType(typeOracle0, jPackage0, "G", "", false, (JTypeParameter[]) null);
      JParameterizedType jParameterizedType0 = jGenericType0.asParameterizedByWildcards();
      DirectRestServiceInterfaceClassCreator directRestServiceInterfaceClassCreator0 = new DirectRestServiceInterfaceClassCreator(treeLogger0, generatorContext0, jParameterizedType0);
      // Undeclared exception!
      try { 
        directRestServiceInterfaceClassCreator0.createComposerFactory();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("com.google.gwt.dev.javac.typemodel.JParameterizedType", e);
      }
  }
}
