/*
 * This file was automatically generated by EvoSuite
 * Tue Jun 18 15:29:36 GMT 2019
 */

package org.apache.storm.kafka;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import clojure.lang.ISeq;
import clojure.lang.LongRange;
import clojure.lang.PersistentHashMap;
import clojure.lang.PersistentTreeMap;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class KafkaSpout_ESTest extends KafkaSpout_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      // EXCEPTION DIFF:
      // The original version did not exhibit this exception:
      //     java.lang.NoClassDefFoundError : Could not initialize class clojure.lang.PersistentTreeMap
      PersistentTreeMap persistentTreeMap0 = PersistentTreeMap.EMPTY;
      ISeq iSeq0 = LongRange.create(0L, 0L);
      // EXCEPTION DIFF:
      // The modified version did not exhibit this exception:
      //     org.evosuite.runtime.mock.java.lang.MockIllegalArgumentException : No value supplied for key: null
      // Undeclared exception!
      try { 
        PersistentHashMap.createWithCheck(iSeq0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No value supplied for key: null
         //
         verifyException("clojure.lang.PersistentHashMap", e);
         assertTrue(e.getMessage().equals("No value supplied for key: null"));   
      }
  }
}
