/*
 * This file was automatically generated by EvoSuite
 * Mon Jun 17 17:28:34 GMT 2019
 */

package br.com;

import org.junit.Test;
import static org.junit.Assert.*;
import br.com.Ball;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Ball_ESTest extends Ball_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Ball ball0 = new Ball(1934L, (-2324), (-2324), "u'Dj", "u'Dj", "u'Dj", "u'Dj", (String) null, "a2zp", "a2zp", "", "u'Dj");
      String string0 = ball0.finalString();
      assertEquals("KafkaSpoutConfig{kafkaProps=null, keyDeserializer=a2zp, valueDeserializer=a2zp, pollTimeoutMs=a2zp, offsetCommitPeriodMs=1934, maxUncommittedOffsets=-2324, firstPollOffsetStrategy=u'Dj, kafkaSpoutStreams=u'Dj, tuplesBuilder=u'Dj, retryService=u'Dj, topics=, topicWildcardPattern=u'Dj}", string0); // (Primitive) Original Value: KafkaSpoutConfig{kafkaProps=null, keyDeserializer=a2zp, valueDeserializer=a2zp, pollTimeoutMs=a2zp, offsetCommitPeriodMs=1934, maxUncommittedOffsets=-2324, firstPollOffsetStrategy=u'Dj, kafkaSpoutStreams=u'Dj, tuplesBuilder=u'Dj, retryService=u'Dj, topics=, topicWildcardPattern=u'Dj} | Regression Value: KafkaSpoutConfig{kafkaProps=null, keyDeserializer=a2zp, valueDeserializer=a2zp, pollTimeoutMs=a2zp, offsetCommitPeriodMs=1934, maxRetries=-2324, maxUncommittedOffsets=-2324, firstPollOffsetStrategy=u'Dj, kafkaSpoutStreams=u'Dj, tuplesBuilder=u'Dj, retryService=u'Dj, topics=, topicWildcardPattern=u'Dj}
  }
}
